In [1]:
#medium article: https://towardsdatascience.com/the-complete-beginners-guide-to-data-cleaning-and-preprocessing-2070b7d4c6d?gi=c5101f25cd16

In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
dataset = pd.read_csv('fake_data.csv')

In [3]:
dataset.head()

animal   age    worth  friendly
0    cat   4.0  72000.0        No
1    Dog  17.0  48000.0       Yes
2  Moose   6.0  54000.0        No
3    Dog   8.0  61000.0        No
4  Moose   4.0      NaN       Yes

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [5]:
imputer = Imputer(missing_values = np.nan, strategy = 'mean', axis = 0) #This will handle missing data with the mean of the column

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [6]:
imputer = imputer.fit(X[:, 1:3]) #put only the columns with possible missing data

In [7]:
X[:, 1:3] = imputer.transform(X[:, 1:3]) #put only the columns with possible missing data

In [8]:
X

array([['cat', 4.0, 72000.0],
       ['Dog', 17.0, 48000.0],
       ['Moose', 6.0, 54000.0],
       ['Dog', 8.0, 61000.0],
       ['Moose', 4.0, 58750.0]], dtype=object)

In [11]:
labelencoder_X = LabelEncoder() #labelEnconder will transform categorical values in numbers
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

In [12]:
X

array([[2, 4.0, 72000.0],
       [0, 17.0, 48000.0],
       [1, 6.0, 54000.0],
       [0, 8.0, 61000.0],
       [1, 4.0, 58750.0]], dtype=object)

In [13]:
# But with this thing above we get a problem, has you can see cat=2 and dog= 0, so we have a hierarchical value, but cat is not necessarily greater than dog

In [14]:
#So we need to create dummy variable, where cat, moose and dogs can be transofrm in columns and we can fill this columns with 0's and 1's

In [19]:
onehotencoder = OneHotEncoder(categorical_features = [0]) #this wiil transform this values in columns

In [20]:
X = onehotencoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [22]:
X

array([[0.000e+00, 0.000e+00, 1.000e+00, 4.000e+00, 7.200e+04],
       [1.000e+00, 0.000e+00, 0.000e+00, 1.700e+01, 4.800e+04],
       [0.000e+00, 1.000e+00, 0.000e+00, 6.000e+00, 5.400e+04],
       [1.000e+00, 0.000e+00, 0.000e+00, 8.000e+00, 6.100e+04],
       [0.000e+00, 1.000e+00, 0.000e+00, 4.000e+00, 5.875e+04]])

In [23]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y) #lets go transform yes and no now

In [25]:
y

array([0, 1, 0, 0, 1])

In [27]:
#Now lets split pur data in train and test

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [29]:
# Now for feature scaling

In [30]:
# As you can se we have a variable age with values from 4 to 17

In [31]:
# And woth with values from 48.000 to 83.000

In [32]:
# Once upon a time worth is much bigger then age thats mean that Euclidean distance will be docimnated by worth and will wind up up dominating the age

In [35]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform([y_train])